x-common-env: &common-env
  POSTGRES_USER: red
  POSTGRES_PASSWORD: red
  POSTGRES_DB: red

services:
  rasa-training:
    build: ./chatbot
    volumes:
      - ./chatbot/models:/app/models:rw
      - ./chatbot/data:/app/data:ro
      - ./chatbot/domain.yml:/app/domain.yml:ro
    command: "train --force"
    networks:
      - red_network
    environment:
      - PYTHONPATH=/app
    restart: "no"  

  rasa:
    build: ./chatbot
    ports:
      - "5005:5005"
    volumes:
      - ./chatbot/models:/app/models:rw
    command: "run --enable-api --cors '*' --debug"
    depends_on:
      rasa-training:
        condition: service_completed_successfully
      action_server:
        condition: service_started
    networks:
      - red_network
    restart: unless-stopped

  action_server:
    build: ./chatbot
    ports:
      - "5055:5055"
    command: "run actions --cors '*'"
    env_file:
      - ./chatbot/database.env
    depends_on:
      rasa-training:
        condition: service_completed_successfully
    networks:
      - red_network
    restart: unless-stopped

  web:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
    depends_on:
      - rasa
    networks:
      - red_network
    restart: unless-stopped

networks:
  red_network:
    driver: bridge

volumes:
  red_data:
    driver: local