x-common-env: &common-env
  POSTGRES_USER: red
  POSTGRES_PASSWORD: red
  POSTGRES_DB: red

services:
  rasa:
    build: ./chatbot  # Build from your chatbot directory
    ports:
      - "5005:5005"
    volumes:
      - ./chatbot/models:/app/models:rw
    command: "run --enable-api --cors '*' --debug"
    depends_on:
      - action_server
    networks:
      - red_network

  action_server:
    build: ./chatbot  # Same build context as rasa service
    ports:
      - "5055:5055"
    command: "run actions --cors '*'"
    env_file:
      - ./chatbot/database.env
    networks:
      - red_network

  web:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
    networks:
      - red_network

networks:
  red_network:
    driver: bridge

volumes:
  red_data:
    driver: local