name: Deploy to Hetzner

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.HETZNER_SSH_KEY }}

      - name: Debug SSH
        run: |
          echo "Testing connection to: 91.99.232.111"
          echo "Using user: root"
          ssh -v -o StrictHostKeyChecking=no root@91.99.232.111 "pwd && whoami"

      - name: Test SSH connection
        run: |
          ssh -o StrictHostKeyChecking=no -o ConnectTimeout=10 \
          root@91.99.232.111 \
          "echo 'SSH connection successful'"

      - name: Copy files to Hetzner
        run: |
          rsync -az --delete --exclude '.git' --exclude 'node_modules' \
          --exclude '.github' --exclude 'README.md' \
          -e "ssh -o StrictHostKeyChecking=no" \
          ./ root@91.99.232.111:/root/app

      - name: Deploy on Hetzner
        run: |
          ssh -o StrictHostKeyChecking=no root@91.99.232.111 << 'EOF'
          cd /root/app
          echo "Pulling latest images..."
          docker compose pull || echo "Pull failed, continuing..."
          echo "Building images..."
          docker compose build --pull
          echo "Starting services..."
          docker compose up -d --remove-orphans
          echo "Deployment completed successfully"
          EOF
